#!/usr/bin/env php
<?php

use Wbot\Application\WbotApplication;

require_once __DIR__ . '/vendor/autoload.php';

if (PHP_SAPI !== 'cli' && PHP_SAPI !== 'phpdbg') {
	fprintf(STDERR, 'Cannot run %s from %s', __FILE__, PHP_SAPI);
	exit(1);
}

if (__FILE__ !== ($file = realpath($argv[0])) && basename(__FILE__) !== basename($file)) {
	fprintf(STDERR, 'Cannot run %s from %s' . PHP_EOL, __FILE__, $file);
	exit(1);
}

$app = new WbotApplication();

$app->add(new Wbot\Command\WbotFetchCommand);
$app->add(new Wbot\Command\WbotServeCommand);

$app->run();
