#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

const SYS_DIR = __DIR__;

define('SRC_DIR', SYS_DIR . DIRECTORY_SEPARATOR . 'src');
define('APP_DIR', SRC_DIR . DIRECTORY_SEPARATOR . 'app');
define('CMD_DIR', SRC_DIR . DIRECTORY_SEPARATOR . 'cmd');

define('RES_DIR', SYS_DIR . DIRECTORY_SEPARATOR . 'res');
define('OUT_DIR', RES_DIR . DIRECTORY_SEPARATOR . 'out');
define('TMP_DIR', RES_DIR . DIRECTORY_SEPARATOR . 'tmp');

if (PHP_SAPI !== 'cli' && PHP_SAPI !== 'phpdbg') {
	fprintf(STDERR, 'Cannot run %s from %s', __FILE__, PHP_SAPI);
	exit(1);
}

if (__FILE__ !== ($file = realpath($argv[0])) && basename(__FILE__) !== basename($file)) {
	fprintf(STDERR, 'Cannot run %s from %s' . PHP_EOL, __FILE__, $file);
	exit(1);
}

$app = new Application('WWW-Robot', '1.0.0');

$app->add(new Ske\Bot\Command\FetchCommand);
$app->add(new Ske\Bot\Command\ServeCommand);

$app->run();
